AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scalable TypeScript Backend API - Cards API

Parameters:
  Env: { Type: String, Default: dev, AllowedValues: [dev, prod], Description: Environment name }

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures: [arm64]
    Environment:
      Variables:
        NODE_ENV: !Ref Env
        TABLE_NAME: !Ref MainTable

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      Cors: { AllowMethods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'", AllowHeaders: "'Content-Type,Authorization'", AllowOrigin: "'*'" }

  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-${Env}-table"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Env

  # GET /heartbeat
  GetHeartbeatFunction:
    Type: AWS::Serverless::Function
    Description: Health check endpoint for API monitoring
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/getHeartbeat.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/getHeartbeat.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /heartbeat
            Method: get

  # ANY /{proxy+}
  NotFoundFunction:
    Type: AWS::Serverless::Function
    Description: Catch-all handler for undefined routes - returns 404
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/notFound.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/notFound.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /{proxy+}
            Method: any

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}"
  TableName:
    Description: "DynamoDB Table Name"
    Value: !Ref MainTable
  TableArn:
    Description: "DynamoDB Table ARN"
    Value: !GetAtt MainTable.Arn
