AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scalable TypeScript Backend API - Cards API

Parameters:
  Env: { Type: String, Default: dev, AllowedValues: [dev, prod], Description: Environment name }
  AuthToken: { Type: String, NoEcho: true, Description: API authentication token for protected endpoints }
  WafHeaderName: { Type: String, NoEcho: true, Description: WAF custom header name for request filtering }
  WafHeaderValue: { Type: String, NoEcho: true, Description: WAF custom header value for request filtering }

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures: [arm64]
    Environment:
      Variables:
        NODE_ENV: !Ref Env
        TABLE_NAME: !Ref MainTable

Resources:
  ApiWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${AWS::StackName}-${Env}-waf"
      Scope: REGIONAL
      DefaultAction:
        Block: {}
      Rules:
        - Name: RequireCustomHeader
          Priority: 1
          Statement:
            ByteMatchStatement:
              SearchString: !Ref WafHeaderValue
              FieldToMatch:
                SingleHeader:
                  Name: !Ref WafHeaderName
              TextTransformations:
                - Priority: 0
                  Type: NONE
              PositionalConstraint: EXACTLY
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RequireCustomHeader
        - Name: RateLimitPerIP
          Priority: 2
          Statement:
            RateBasedStatement:
              Limit: 500
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitPerIP
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${AWS::StackName}-${Env}-waf"

  ApiWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${MyApi}/stages/${Env}"
      WebACLArn: !GetAtt ApiWebACL.Arn

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      MinimumCompressionSize: 0
      Auth:
        Authorizers:
          ApiAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            FunctionPayloadType: REQUEST
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 300
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'"
        AllowHeaders: !Sub "'Content-Type,Authorization,${WafHeaderName}'"
        AllowOrigin: "'*'"
  
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/authorizer.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/authorizer.handler
      Environment:
        Variables:
          AUTH_TOKEN: !Ref AuthToken

  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-${Env}-table"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Env

  GetHeartbeatFunction:
    Type: AWS::Serverless::Function
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/getHeartbeat.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/getHeartbeat.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /heartbeat
            Method: get


  GetProtectedExampleFunction:
    Type: AWS::Serverless::Function
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/getProtectedExample.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/getProtectedExample.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /protected/example
            Method: get
            Auth:
              Authorizer: ApiAuthorizer

  GetUserInventoryFunction:
    Type: AWS::Serverless::Function
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/getUserInventory.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/getUserInventory.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/inventory/{userId}
            Method: get


  MarketplaceBuyFunction:
    Type: AWS::Serverless::Function
    Timeout: 10
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceBuy.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceBuy.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/buy
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  MarketplaceFindActiveSellersFunction:
    Type: AWS::Serverless::Function
    Timeout: 10
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceFindActiveSellers.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceFindActiveSellers.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/find-sellers
            Method: get


  MarketplaceGetHistoryFunction:
    Type: AWS::Serverless::Function
    Timeout: 10
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceGetHistory.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceGetHistory.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/history
            Method: get


  MarketplaceGetListingsFunction:
    Type: AWS::Serverless::Function
    Timeout: 5
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceGetListings.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceGetListings.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/listings/{userId}
            Method: get


  MarketplaceListFunction:
    Type: AWS::Serverless::Function
    Timeout: 5
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceList.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceList.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/list
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  MarketplaceToggleActiveSellerFunction:
    Type: AWS::Serverless::Function
    Timeout: 5
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceToggleActiveSeller.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceToggleActiveSeller.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/sellers/toggle
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  MarketplaceUnlistFunction:
    Type: AWS::Serverless::Function
    Timeout: 5
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceUnlist.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceUnlist.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/unlist
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  ModifyUserInventoryFunction:
    Type: AWS::Serverless::Function
    Timeout: 5
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/modifyUserInventory.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/modifyUserInventory.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/inventory/modify
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  TransferBetweenUsersFunction:
    Type: AWS::Serverless::Function
    Timeout: 10
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/transferBetweenUsers.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/transferBetweenUsers.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /transfer
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  NotFoundFunction:
    Type: AWS::Serverless::Function
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/notFound.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/notFound.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /{proxy+}
            Method: any


Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}"
  TableName:
    Description: "DynamoDB Table Name"
    Value: !Ref MainTable
  TableArn:
    Description: "DynamoDB Table ARN"
    Value: !GetAtt MainTable.Arn
