AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scalable TypeScript Backend API - Cards API

Parameters:
  Env: { Type: String, Default: dev, AllowedValues: [dev, prod], Description: Environment name }
  AuthToken: { Type: String, NoEcho: true, Description: API authentication token for protected endpoints }
  WafHeaderName: { Type: String, NoEcho: true, Description: WAF custom header name for request filtering }
  WafHeaderValue: { Type: String, NoEcho: true, Description: WAF custom header value for request filtering }

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs20.x
    Architectures: [arm64]
    Environment:
      Variables:
        NODE_ENV: !Ref Env
        TABLE_NAME: !Ref MainTable

Resources:
  # WAF Web ACL for API Protection
  ApiWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub "${AWS::StackName}-${Env}-waf"
      Scope: REGIONAL
      DefaultAction:
        Block: {}
      Rules:
        # Rule 1: Require specific header
        - Name: RequireCustomHeader
          Priority: 1
          Statement:
            ByteMatchStatement:
              SearchString: !Ref WafHeaderValue
              FieldToMatch:
                SingleHeader:
                  Name: !Ref WafHeaderName
              TextTransformations:
                - Priority: 0
                  Type: NONE
              PositionalConstraint: EXACTLY
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RequireCustomHeader
        
        # Rule 2: Rate limiting per IP (100 requests per 5 minutes)
        - Name: RateLimitPerIP
          Priority: 2
          Statement:
            RateBasedStatement:
              Limit: 100
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitPerIP
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub "${AWS::StackName}-${Env}-waf"

  # Associate WAF with API Gateway
  ApiWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${MyApi}/stages/${Env}"
      WebACLArn: !GetAtt ApiWebACL.Arn

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      MinimumCompressionSize: 0
      Auth:
        Authorizers:
          ApiAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            FunctionPayloadType: REQUEST
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 300
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,PATCH,OPTIONS'"
        AllowHeaders: !Sub "'Content-Type,Authorization,${WafHeaderName}'"
        AllowOrigin: "'*'"
  
  # Lambda Authorizer Function
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/authorizer.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/authorizer.handler
      Environment:
        Variables:
          AUTH_TOKEN: !Ref AuthToken

  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-${Env}-table"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Env

  # GET /heartbeat
  GetHeartbeatFunction:
    Type: AWS::Serverless::Function
    Description: Health check endpoint for API monitoring
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/getHeartbeat.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/getHeartbeat.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /heartbeat
            Method: get


  # GET /protected/example [AUTH REQUIRED]
  GetProtectedExampleFunction:
    Type: AWS::Serverless::Function
    Description: Example protected endpoint that requires authentication
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/getProtectedExample.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/getProtectedExample.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /protected/example
            Method: get
            Auth:
              Authorizer: ApiAuthorizer

  # GET /user/inventory/{userId}
  GetUserInventoryFunction:
    Type: AWS::Serverless::Function
    Description: Retrieves a user's inventory
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/getUserInventory.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/getUserInventory.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/inventory/{userId}
            Method: get


  # POST /marketplace/buy [AUTH REQUIRED]
  MarketplaceBuyFunction:
    Type: AWS::Serverless::Function
    Description: Purchases a card or pack from the marketplace
    Timeout: 10
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceBuy.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceBuy.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/buy
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  # GET /marketplace/history
  MarketplaceGetHistoryFunction:
    Type: AWS::Serverless::Function
    Description: Get RAP history for all cards and packs with marketplace activity
    Timeout: 10
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceGetHistory.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceGetHistory.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/history
            Method: get


  # GET /marketplace/listings/{userId}
  MarketplaceGetListingsFunction:
    Type: AWS::Serverless::Function
    Description: Get all marketplace listings for a specific user
    Timeout: 5
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceGetListings.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceGetListings.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/listings/{userId}
            Method: get


  # POST /marketplace/list [AUTH REQUIRED]
  MarketplaceListFunction:
    Type: AWS::Serverless::Function
    Description: Lists a card or pack for sale on the marketplace (max 50 per user)
    Timeout: 5
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceList.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceList.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/list
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  # POST /marketplace/unlist [AUTH REQUIRED]
  MarketplaceUnlistFunction:
    Type: AWS::Serverless::Function
    Description: Unlists an item from the marketplace
    Timeout: 5
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/marketplaceUnlist.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/marketplaceUnlist.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /marketplace/unlist
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  # POST /user/inventory/modify [AUTH REQUIRED]
  ModifyUserInventoryFunction:
    Type: AWS::Serverless::Function
    Description: Modifies a user's inventory
    Timeout: 5
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/modifyUserInventory.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/modifyUserInventory.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/inventory/modify
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  # POST /transfer [AUTH REQUIRED]
  TransferBetweenUsersFunction:
    Type: AWS::Serverless::Function
    Description: Atomically execute multi-way trades between users
    Timeout: 10
    MemorySize: 256
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/transferBetweenUsers.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/transferBetweenUsers.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /transfer
            Method: post
            Auth:
              Authorizer: ApiAuthorizer

  # ANY /{proxy+}
  NotFoundFunction:
    Type: AWS::Serverless::Function
    Description: Catch-all handler for undefined routes - returns 404
    Timeout: 3
    MemorySize: 128
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/handlers/notFound.ts
    Properties:
      CodeUri: ./
      Handler: src/handlers/notFound.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MainTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /{proxy+}
            Method: any


Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${Env}"
  TableName:
    Description: "DynamoDB Table Name"
    Value: !Ref MainTable
  TableArn:
    Description: "DynamoDB Table ARN"
    Value: !GetAtt MainTable.Arn
